### ISSUE TITLE
没有请求 “/fjqndxx/v1/app/big_study/user/loginByMp”

### ISSUE THREAD

**Issue by umeiko** [838239178/fjqndxx-v2#114]
### 内容

抓取后没找到请求“/fjqndxx/v1/app/big_study/user/loginByMp”，但是有比较相似的“https://api.iyunci.cn/fjqndxx/v1/app/big_study/platform/checkuser?code=XXXX”，这个响应里“mp_openid"=null，但是有“unionid”和“openid”。

**Comment by 838239178** [comment]
可能是又改回去了 别用 会被查

**Comment by umeiko** [comment]
因为新系统才上线，等过个几个月不怎么维护了可以再看
